[adapters]
default = "testaruda-adapter-rust"

[discover]
exclude = [ "target", ".git", "node_modules", ".venv", "venv", "__pycache__", ".mypy_cache", ".pytest_cache", "build", "dist", ".tox",]

[adapters.extensions]
".rs" = "testaruda-adapter-rust"
".py" = "testaruda-adapter-python"
