//! Topic guides for `wai way <topic>`.

use crate::config::{SKILLS_DIR, agent_config_dir};
use std::path::Path;

const AI_GUIDE: &str = r#"> *Facilitation guide generated by `wai way ai` — instructs an LLM to lead an interactive discussion with the user.*

# AI-Assisted Development Guide

**TL;DR**: Walk through 5 topics to configure AI-assisted development. For each:
explain trade-offs, ask the user's preference, generate files. By the end,
the user will have CLAUDE.md, llm.txt, and/or agent skills configured.
CLAUDE.md: {claude_md}. llm.txt: {llm_txt}. Skills: {skills}.

You are helping the user configure their repository for effective AI-assisted
development. Walk through the topics below **one at a time**, asking about
their AI workflow before generating files.

## Current State

- **CLAUDE.md**: {claude_md}
- **AGENTS.md**: {agents_md}
- **llm.txt**: {llm_txt}
- **Agent skills**: {skills}

## Discussion Topics

### 1. AI Instruction File
A persistent file that gives AI assistants project context and rules.
- **CLAUDE.md** — read by Claude Code automatically. Project conventions,
  architecture notes, \"do this / don't do that\" rules.
- **AGENTS.md** — similar, used by some other AI tools.
- **What to include**: coding style, test conventions, architecture overview,
  known gotchas, forbidden patterns, preferred libraries.
- **What NOT to include**: things derivable from code, ephemeral state.
- **→ Ask:** Which AI tools does the team use? What mistakes does the AI
  keep making that instructions could prevent? What context is hardest
  for the AI to figure out on its own?

### 2. Agent Config Sync (wai sync)
Ensure that AI instructions and skills are available to the tools that
need them.
- **projections** — define how `.wai/resources/agent-config/` content
  is synced to `.agents/`, `.claude/commands/`, etc.
- **wai sync** — the command that applies these projections.
- **→ Ask:** Have they configured `.projections.yml`? Do they want to
  sync skills to a standard location like `.agents/`?

### 3. LLM Context File (llm.txt)
Machine-readable project summary for LLMs. Lives at `llm.txt` in the root.
- Purpose: gives any LLM a quick orientation — what the project does,
  key files, entry points, architecture.
- Standard: https://llmstxt.org
- Different from CLAUDE.md — llm.txt is a neutral summary, not rules.
- **→ Ask:** Do they want a general-purpose LLM context file? What should
  it cover — public API surface, architecture, or both?

### 3. Agent Skills
Reusable workflow definitions that enhance AI agent behavior.
- Stored in `.wai/resources/agent-config/skills/` (or equivalent).
- Examples: structured commit workflow, iterative review (Rule of 5),
  code review checklist, PR creation workflow.
- Each skill is a markdown file with frontmatter (name, trigger, aliases).
- **→ Ask:** What repetitive workflows could be codified as skills? Do they
  want the recommended defaults (rule-of-5, commit)?
  Run `wai way --fix skills` to scaffold them.

### 4. Subdirectory Instructions
For monorepos or projects with distinct areas, per-directory instruction
files can scope AI behavior.
- `frontend/CLAUDE.md` — React-specific conventions
- `backend/CLAUDE.md` — API-specific patterns
- These supplement the root file, not replace it.
- **→ Ask:** Does the project have distinct areas that need different AI
  guidance? Is it a monorepo?

### 5. Context Management
Help the AI work efficiently with the codebase.
- Keep CLAUDE.md concise — it's loaded into every conversation.
- Move detailed reference material to linked files the AI can read
  on demand (architecture docs, API specs).
- Use `wai reflect` to periodically synthesize project patterns.
- **→ Ask:** Is the CLAUDE.md getting too long? Are there docs the AI
  should reference but doesn't need in every conversation?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  and explain why.
- Start with CLAUDE.md — it has the highest impact for Claude Code users.
- Write instructions as rules, not essays. "Use snake_case for file names"
  beats a paragraph explaining why.
- Review and update AI instructions periodically — stale rules are
  worse than no rules.
- Test instructions by starting a fresh conversation and seeing
  if the AI behaves as expected.
"#;

pub(crate) fn guide_ai(repo_root: &Path) -> String {
    let has_claude_md = repo_root.join("CLAUDE.md").exists();
    let has_agents_md = repo_root.join("AGENTS.md").exists();
    let has_llm_txt = repo_root.join("llm.txt").exists();
    let has_skills = agent_config_dir(repo_root).join(SKILLS_DIR).is_dir();

    let claude_md = if has_claude_md {
        "detected"
    } else {
        "not present"
    };
    let agents_md = if has_agents_md {
        "detected"
    } else {
        "not present"
    };
    let llm_txt = if has_llm_txt {
        "detected"
    } else {
        "not present"
    };
    let skills = if has_skills {
        "configured"
    } else {
        "not configured"
    };
    AI_GUIDE
        .replace("{claude_md}", claude_md)
        .replace("{llm_txt}", llm_txt)
        .replace("{skills}", skills)
        .replace("{agents_md}", agents_md)
}
