//! Topic guides for `wai way <topic>`.

use std::path::Path;

const CI_GUIDE: &str = r#"> *Facilitation guide generated by `wai way ci` — instructs an LLM to lead an interactive discussion with the user.*

# CI Setup Guide

**TL;DR**: Walk through 10 topics to build a CI pipeline. For each: explain
trade-offs, ask the user's preference, generate config. By the end, the user
will have a working CI configuration tailored to their repository.
Current state: {current_state}. Ecosystems: {ecosystem_line}.

You are helping the user set up continuous integration for this repository.
Walk through the topics below **one at a time**, asking the user about their
preferences and constraints before generating any configuration. Do not dump
an entire CI config upfront — build it up topic by topic.

## Current State

- **CI status**: {current_state}
- **Ecosystems**: {ecosystem_line}

## Discussion Topics

Work through these in order. For each one, explain the trade-offs briefly,
ask what the user wants, then move on.

### 1. CI Platform
If no CI is configured yet, ask which platform they want (GitHub Actions,
GitLab CI, CircleCI, etc.). If one is already detected, confirm they want
to keep it or migrate.

### 2. Workflow Separation
Should checks be split into separate workflows/jobs or combined?
- **Separate workflows**: lint, test, build each in their own file — easier
  to re-run individually, clearer failure signals, can have different triggers.
- **Single workflow, multiple jobs**: one file, jobs run in parallel — simpler
  to manage, shared trigger config.
- **→ Ask:** Do they want lint/format checks separate from tests? Should builds
  (release artifacts) be a separate workflow?

### 3. Triggers
Which events should start CI?
- Pull requests (which branches?)
- Pushes to main/develop
- Tags (for releases)
- Manual dispatch
- Scheduled (nightly builds, dependency checks)
- Path filters — skip CI when only docs change?

### 4. Caching
Caching build dependencies dramatically speeds up CI. Discuss:
- **What to cache**: dependency downloads, build artifacts, tool binaries
- **Cache keys**: use lockfile hashes (Cargo.lock, package-lock.json, go.sum)
- **Cache scope**: per-branch with main fallback
- Platform-specific: `actions/cache`, `sccache` for Rust, `node_modules`
  caching for JS, Go module cache

### 5. Matrix Builds
Should CI test across multiple configurations?
- OS matrix (ubuntu, macos, windows)
- Language version matrix (rustc stable/nightly, node 18/20/22, python 3.11/3.12)
- Feature flags or build variants
- **→ Ask:** What's the minimum they need vs what's nice to have?
  More matrix entries = slower + more expensive.

### 6. Linting & Formatting
If the user mentions they already configured hooks or linting locally,
skip the overlap and focus on what CI adds (enforcing checks that
developers could skip locally).
- Code formatting (rustfmt, prettier, black, gofmt)
- Linters (clippy, eslint, ruff, golangci-lint)
- Type checking (tsc, mypy, pyright)
- Spell checking (typos)
- Prose linting (vale)
- Should these block merge or just warn?

### 7. Testing
If the user mentions they already configured coverage, skip the overlap
and focus on CI-specific concerns like parallelism, services, and merge blocking.
- Unit tests vs integration tests (separate jobs?)
- Test coverage — should CI enforce a threshold?
- Flaky test handling — retries?
- Test parallelism
- Do any tests need services (databases, Redis, etc.)?

### 8. Security & Secrets
- Dependency auditing (cargo audit, npm audit, pip-audit)
- Secret scanning
- SAST / code scanning (CodeQL, semgrep)
- How are secrets managed? (GitHub secrets, Vault, etc.)
- Should PRs from forks have restricted access?

### 9. Artifacts & Deployment
- Should CI produce build artifacts?
- Release automation (on tag push?)
- Container image builds
- Deploy previews for PRs
- Where do releases go? (GitHub Releases, npm, crates.io, PyPI, Docker Hub)

### 10. Performance & Cost
- Timeouts — what's a reasonable max for the whole pipeline?
- `fail-fast` — cancel other matrix jobs on first failure?
- Concurrency — cancel in-progress runs when a new push arrives?
- Self-hosted runners vs hosted — any cost constraints?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  based on the detected ecosystem and explain why.
- Generate config incrementally as decisions are made.
- Use the detected ecosystem to suggest sensible defaults.
- Prefer simple, maintainable configs over clever ones.
- Pin action versions to SHA for security (e.g. `actions/checkout@<sha>`)
  — `@v4` is common but vulnerable to tag mutation.
- Add comments in generated YAML explaining non-obvious choices.
"#;

fn detect_ci_state(repo_root: &Path) -> String {
    let has_github_actions = repo_root.join(".github/workflows").is_dir();
    let has_gitlab_ci = repo_root.join(".gitlab-ci.yml").exists();
    let has_circleci = repo_root.join(".circleci/config.yml").exists();

    if has_github_actions {
        let count = std::fs::read_dir(repo_root.join(".github/workflows"))
            .ok()
            .map(|entries| {
                entries
                    .filter_map(|e| e.ok())
                    .filter(|e| {
                        e.path()
                            .extension()
                            .and_then(|ext| ext.to_str())
                            .is_some_and(|ext| ext == "yml" || ext == "yaml")
                    })
                    .count()
            })
            .unwrap_or(0);
        format!(
            "GitHub Actions detected ({} workflow(s) in .github/workflows/)",
            count
        )
    } else if has_gitlab_ci {
        "GitLab CI detected (.gitlab-ci.yml)".to_string()
    } else if has_circleci {
        "CircleCI detected (.circleci/config.yml)".to_string()
    } else {
        "No CI configuration detected".to_string()
    }
}

fn detect_ecosystem_line(repo_root: &Path) -> String {
    let has_cargo = repo_root.join("Cargo.toml").exists();
    let has_package_json = repo_root.join("package.json").exists();
    let has_go_mod = repo_root.join("go.mod").exists();
    let has_pyproject = repo_root.join("pyproject.toml").exists();

    let mut ecosystems = Vec::new();
    if has_cargo {
        ecosystems.push("Rust");
    }
    if has_package_json {
        ecosystems.push("Node.js");
    }
    if has_go_mod {
        ecosystems.push("Go");
    }
    if has_pyproject {
        ecosystems.push("Python");
    }

    if ecosystems.is_empty() {
        "No recognized language ecosystem detected.".to_string()
    } else {
        format!("Detected: {}", ecosystems.join(", "))
    }
}

pub(crate) fn guide_ci(repo_root: &Path) -> String {
    // Detect current state to give the LLM context
    let current_state = detect_ci_state(repo_root);

    // Detect language/ecosystem for tailored advice
    let ecosystem_line = detect_ecosystem_line(repo_root);
    CI_GUIDE
        .replace("{current_state}", &current_state)
        .replace("{ecosystem_line}", &ecosystem_line)
}
