//! Topic guides for `wai way <topic>`.

use std::path::Path;
const CODE_QUALITY_GUIDE: &str = r#"> *Facilitation guide generated by `wai way code-quality` — instructs an LLM to lead an interactive discussion with the user.*

# Code Quality Guide

**TL;DR**: Walk through 6 topics to set up structural code quality checks using pretender. For each: explain what it does, ask the user's preference, generate config. By the end, the user will have pretender configured with thresholds, a pre-commit hook, and CI integration.
Current state: {pretender_status}.

You are helping the user set up structural code quality checks for this repository.
Walk through the topics below **one at a time**, asking about their project
languages and preferences before generating configuration.

## Current State

- **pretender**: {pretender_status}

## Discussion Topics

### 1. What pretender does
pretender is a CLI tool that analyzes source code using tree-sitter AST parsers.
It computes structural metrics and compares them against configurable thresholds:

| Metric | What it measures | Default threshold |
|--------|-----------------|-------------------|
| cyclomatic | 1 + decision points per function | 10 |
| cognitive | Nesting-weighted branch sum | 15 |
| abc | √(A²+B²+C²) assignment/branch/condition | 30 |
| function_lines | Lines per function body | 40 |
| file_lines | Total lines per file | 400 |
| nesting_max | Maximum control-flow depth | 3 |
| params | Formal parameter count | 4 |

**Supported languages**: Python, Rust, Go, JavaScript, TypeScript, Java, Ruby, C, C++, C#, Julia, Clojure, R

- **→ Ask:** What languages does this project use? Are they on the supported list?

### 2. Installation
```bash
cargo install pretender
```

Verify: `pretender --version`

- **→ Ask:** Do they have the Rust toolchain installed? If not, suggest `rustup.rs`.

### 3. Configuration
Run the interactive wizard:
```bash
pretender init --non-interactive
```

This creates `pretender.toml` at the repo root with sensible defaults:
```toml
[pretender]
mode = "tiered"
languages = ["auto"]

[thresholds]
cyclomatic_max = 10
cognitive_max = 15
function_lines_max = 40
file_lines_max = 400
nesting_max = 3
params_max = 4
abc_max = 30
```

- **→ Ask:** Do they want to start with the defaults, or customize thresholds now?

### 4. Running checks
```bash
pretender check .
```

Output shows per-function metrics with green/yellow/red bands:
- ✓ OK — all metrics within thresholds
- ● HIGH — one or more metrics exceed the red band
- ◐ MEDIUM — metrics in the yellow band
- ○ LOW — guidance-only hint

For complexity:
```bash
pretender complexity src/
```

For structural duplication:
```bash
pretender duplication src/
```

- **→ Ask:** Should they start with `pretender check .` on the whole repo, or just specific directories?

### 5. Pre-commit hook
Prevent violations from reaching the repository:
```bash
pretender hooks install
```

This writes a `.git/hooks/pre-commit` script that runs `pretender check .` on staged files.

- **→ Ask:** Do they want a pre-commit hook? Or should checks only run in CI?

### 6. CI integration
Generate a GitHub Actions workflow:
```bash
pretender ci generate github
```

This writes `.github/workflows/pretender.yml` that runs `pretender check` on every PR.

- **→ Ask:** Do they use GitHub Actions? Should checks gate merges (gate mode) or just warn (tiered mode)?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest the defaults above.
- Generate config incrementally as decisions are made.
- Suggest `just complexity` recipe if a justfile exists.
- pretender is most valuable in polyglot repos where native linters don't cover all languages.
"#;

pub(crate) fn guide_code_quality(repo_root: &Path) -> String {
    let has_pretender_bin = std::process::Command::new("pretender")
        .arg("--version")
        .output()
        .ok()
        .is_some_and(|o| o.status.success());

    let has_pretender_config = repo_root.join("pretender.toml").exists();

    let pretender_status = if has_pretender_bin {
        if has_pretender_config {
            "pretender installed and configured".to_string()
        } else {
            "pretender installed but not configured (no pretender.toml)".to_string()
        }
    } else {
        "pretender not installed".to_string()
    };
    CODE_QUALITY_GUIDE.replace("{pretender_status}", &pretender_status)
}
