//! Topic guides for `wai way <topic>`.

use std::path::Path;
const COVERAGE_GUIDE: &str = r#"> *Facilitation guide generated by `wai way coverage` — instructs an LLM to lead an interactive discussion with the user.*

# Test Coverage Guide

**TL;DR**: Walk through 6 topics to set up test coverage. For each: explain
trade-offs, ask the user's preference, generate config. By the end, the user
will have coverage tooling with thresholds and reporting configured.
Current state: {current_state}. Ecosystems: {ecosystem_line}.

You are helping the user set up test coverage for this repository.
Walk through the topics below **one at a time**, asking about their
goals and constraints before generating configuration.

## Current State

- **Coverage tools**: {current_state}
- **Ecosystems**: {ecosystem_line}

## Discussion Topics

### 1. Coverage Tool
Which tool should measure coverage?
- **Rust**: `cargo-tarpaulin` (easy setup, good defaults) or `cargo-llvm-cov`
  (more accurate, uses LLVM instrumentation). tarpaulin is simpler;
  llvm-cov is more precise, requires `llvm-tools-preview` component.
- **Python**: `coverage.py` / `pytest-cov` — the standard. Works with
  pytest out of the box.
- **JS/TS**: `vitest` has built-in coverage, or `c8`/`nyc` (istanbul).
- **Go**: `go test -cover` built-in. Use `go tool cover` for reports.
- **→ Ask:** Do they already have a preference? Any constraints?

### 2. Coverage Threshold
Should the project enforce a minimum coverage percentage?
- **Why**: prevents regressions — new code without tests gets caught.
- **Starting point**: don't aim for 100%. Pick a realistic baseline
  (measure current coverage first) and ratchet up over time.
- **How to enforce**: `fail-under` (tarpaulin/coverage.py), `thresholds`
  (vitest), CI check.
- **→ Ask:** Do they want a hard threshold? What feels realistic — 60%? 80%?
  Should it block merges or just report?

### 3. What to Measure
Not all code is equally worth covering.
- **Include**: business logic, data transformations, error handling paths.
- **Exclude**: generated code, test utilities, CLI scaffolding, migration
  files, vendored dependencies.
- **→ Ask:** Are there directories or patterns that should be excluded from
  coverage? (e.g. `tests/`, `benches/`, `migrations/`, `vendor/`)

### 4. Coverage Reporting
Where should coverage reports go?
- **Local**: HTML reports for developer inspection (`tarpaulin --out Html`,
  `coverage html`, `vitest --coverage`).
- **CI**: upload to a service for PR-level feedback.
  - **Codecov** — free for open source, PR comments with diff coverage.
  - **Coveralls** — similar, good GitHub integration.
  - **CI-only** — just print the number, fail if below threshold.
- **→ Ask:** Do they want a reporting service, or is a CI threshold enough?

### 5. Diff Coverage vs Total Coverage
- **Total coverage**: overall project percentage. Can be gamed by deleting
  untested code. Useful as a baseline.
- **Diff coverage**: coverage of *changed lines only*. Ensures new code
  is tested without penalizing legacy gaps.
- Services like Codecov support both.
- **→ Ask:** Do they care more about overall project coverage or ensuring
  new PRs are well-tested?

### 6. Integration with CI
- Should coverage run on every PR, or only on pushes to main?
- How long does the test suite take? Coverage adds overhead (10-30%).
- Should coverage failure block merge?
- **→ Ask:** Where in the pipeline should this run?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  based on the detected ecosystem and explain why.
- Start by measuring current coverage before setting a threshold.
- Suggest `fail-under` / `thresholds` in config, not just CI scripts,
  so it works locally too.
- Recommend excluding test files and generated code from coverage.
- If they have no tests yet, suggest starting with coverage tooling
  anyway — it creates the habit.
"#;

pub(crate) fn guide_coverage(repo_root: &Path) -> String {
    let has_cargo = repo_root.join("Cargo.toml").exists();
    let has_package_json = repo_root.join("package.json").exists();
    let has_pyproject = repo_root.join("pyproject.toml").exists();
    let has_go_mod = repo_root.join("go.mod").exists();

    let has_tarpaulin = repo_root.join("tarpaulin.toml").exists()
        || std::fs::read_to_string(repo_root.join("Cargo.toml"))
            .ok()
            .is_some_and(|c| c.contains("[package.metadata.tarpaulin]"));
    let has_codecov =
        repo_root.join(".codecov.yml").exists() || repo_root.join("codecov.yml").exists();
    let has_coveralls = repo_root.join(".coveralls.yml").exists();

    let mut detected = Vec::new();
    if has_tarpaulin {
        detected.push("tarpaulin");
    }
    if has_codecov {
        detected.push("codecov");
    }
    if has_coveralls {
        detected.push("coveralls");
    }

    let current_state = if detected.is_empty() {
        "No coverage tools detected".to_string()
    } else {
        format!("Detected: {}", detected.join(", "))
    };

    let mut ecosystems = Vec::new();
    if has_cargo {
        ecosystems.push("Rust");
    }
    if has_package_json {
        ecosystems.push("Node.js");
    }
    if has_pyproject {
        ecosystems.push("Python");
    }
    if has_go_mod {
        ecosystems.push("Go");
    }

    let ecosystem_line = if ecosystems.is_empty() {
        "No recognized language ecosystem detected.".to_string()
    } else {
        ecosystems.join(", ")
    };
    COVERAGE_GUIDE
        .replace("{current_state}", &current_state)
        .replace("{ecosystem_line}", &ecosystem_line)
}
