//! Topic guides for `wai way <topic>`.

use std::path::Path;
const DEVXP_GUIDE: &str = r#"> *Facilitation guide generated by `wai way devxp` — instructs an LLM to lead an interactive discussion with the user.*

# Developer Experience Guide

**TL;DR**: Walk through 6 topics to improve developer experience. For each:
explain trade-offs, ask the user's preference, generate config. By the end,
the user will have editor config, task runner, and environment setup.
EditorConfig: {editorconfig}. Task runner: {task_runner}. Dev container: {devcontainer}.

You are helping the user improve the developer experience in this repository.
Walk through the topics below **one at a time**, asking about their team's
tools and workflows before generating configuration.

## Current State

- **EditorConfig**: {editorconfig}
- **Dev container**: {devcontainer}
- **Task runner**: {task_runner}

## Discussion Topics

### 1. EditorConfig
Consistent formatting across every editor, without extra plugins.
- Defines indent style (tabs vs spaces), indent size, line endings,
  trailing whitespace, final newline.
- Supported by most editors (VS Code via extension, JetBrains built-in, Vim via plugin).
- **→ Ask:** Tabs or spaces? Indent size (2, 4)? Any per-language overrides
  (e.g. 2 spaces for YAML, 4 for Rust)?

### 2. Task Runner
A single entry point for common operations — build, test, lint, format, docs.
- **justfile** — simple, cross-platform, no dependencies beyond `just`.
  Supports arguments, dependencies between recipes, dotenv loading.
  https://just.systems
- **Makefile** — ubiquitous but quirky syntax. Works everywhere.
- **npm scripts** — good if the project is Node.js-only.
- **Taskfile (go-task)** — YAML-based, cross-platform.
- **→ Ask:** Which tool? What are the most common tasks they run?
  Suggested recipes: `build`, `test`, `lint`, `fmt`, `check`, `docs`,
  `dev`/`serve`, `clean`, `install`.

### 3. Dev Containers
Reproducible development environments that "just work".
- **devcontainer.json** — VS Code / GitHub Codespaces / DevPod standard.
- Defines: base image, extensions, port forwarding, post-create commands,
  environment variables, features (e.g. Rust, Node, Docker-in-Docker).
- **→ Ask:** Do team members use different OSes or machine setups? Do they
  use Codespaces or similar? Which tools/runtimes must be in the
  container? Any services needed (database, Redis)?

### 4. Environment Variables
How does the project handle configuration?
- `.env` files (with `.env.example` committed, `.env` gitignored)
- `direnv` with `.envrc` — auto-loads env vars when entering the directory
- **→ Ask:** Do they use env vars for configuration? Should there be a
  template `.env.example`? Do they use `direnv`?

### 5. IDE Configuration
Shared settings that help the whole team.
- `.vscode/settings.json` — format on save, recommended extensions,
  ruler position, file associations.
- `.vscode/extensions.json` — recommended extensions list.
- `.idea/` — JetBrains shared run configs, code style.
- **→ Ask:** Does the team use a common editor? Should shared settings
  be committed or left to individual preference?

### 6. Local Development Server
For projects with a development server or watch mode.
- `just dev` or `just serve` recipe
- Hot reloading / watch mode configuration
- Port conventions
- **→ Ask:** Is there a dev server? What command starts it? Should it
  be standardized in the task runner?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  based on the detected ecosystem and explain why.
- Start with editorconfig and task runner — biggest bang for effort.
- Dev containers are high-effort, high-reward — suggest only if there's
  onboarding pain or environment inconsistency.
- Don't over-configure IDE settings — keep them minimal and optional.
- Task runner recipes should mirror CI steps (if `just lint` passes
  locally, CI lint should also pass).
"#;

pub(crate) fn guide_devxp(repo_root: &Path) -> String {
    let has_editorconfig = repo_root.join(".editorconfig").exists();
    let has_devcontainer =
        repo_root.join(".devcontainer").is_dir() || repo_root.join(".devcontainer.json").exists();
    let has_justfile = repo_root.join("justfile").exists();
    let has_makefile = repo_root.join("Makefile").exists();

    let task_runner = if has_justfile {
        "justfile detected"
    } else if has_makefile {
        "Makefile detected"
    } else {
        "No task runner detected"
    };

    let editorconfig = if has_editorconfig {
        "detected"
    } else {
        "not configured"
    };
    let devcontainer = if has_devcontainer {
        "detected"
    } else {
        "not configured"
    };
    DEVXP_GUIDE
        .replace("{editorconfig}", editorconfig)
        .replace("{task_runner}", task_runner)
        .replace("{devcontainer}", devcontainer)
}
