//! Topic guides for `wai way <topic>`.

use crate::commands::way::checks::detect_doc_tool;
use std::path::Path;

const DOCS_GUIDE: &str = r#"> *Facilitation guide generated by `wai way docs` — instructs an LLM to lead an interactive discussion with the user.*

# Documentation Guide

**TL;DR**: Walk through 7 topics to set up project documentation. For each:
explain trade-offs, ask the user's preference, generate files. By the end,
the user will have README, LICENSE, and doc tooling configured.
Present: {present}. Missing: {missing}.

You are helping the user set up project documentation for this repository.
Walk through the topics below **one at a time**, asking about their
audience and goals before generating files.

## Current State

- **Present**: {present}
- **Missing**: {missing}
- **Doc tool**: {doc_tool_line}

## Discussion Topics

### 1. README
The front door of the project.
- **Audience**: is this for end-users, developers, or both?
- **Sections**: project name + one-liner, badges, install, quick start,
  usage examples, configuration, contributing link, license.
- **Tone**: formal/corporate or casual/community?
- **→ Ask:** What's the project about in one sentence? Who reads the README?

### 2. License
- **Open source?** If yes, which license? (MIT, Apache 2.0, GPL, etc.)
- **Not open source?** A proprietary notice or "All rights reserved".
- **Dual licensing?** Some projects use MIT + Apache 2.0.
- **→ Ask:** Is this open source? Do they have a preferred license?

### 3. Contributing Guide
Who can contribute, and how?
- Development setup instructions
- Branch naming and PR conventions
- Code style and testing requirements
- Code of conduct reference
- **→ Ask:** Do they accept outside contributions? What should contributors
  know before submitting a PR?

### 4. .gitignore
What should stay out of version control?
- Language-specific build artifacts
- IDE/editor files (.idea/, .vscode/, *.swp)
- OS files (.DS_Store, Thumbs.db)
- Secrets and env files (.env, *.key)
- **→ Ask:** Any custom paths or patterns to ignore? Using a template
  from gitignore.io is a good starting point.

### 5. API / Reference Documentation
Generated documentation from source code.
- **Rust**: `cargo doc` — built-in, doc comments become HTML.
- **Python**: Sphinx, MkDocs + mkdocstrings, pdoc.
- **JS/TS**: TypeDoc, JSDoc.
- **Go**: godoc — built-in.
- **→ Ask:** Do they need generated API docs? Should they be published
  (GitHub Pages, ReadTheDocs)?

### 6. Docs Directory
A `docs/` folder for long-form documentation beyond the README.
- Architecture docs, design decisions, tutorials, guides.
- Should it use a static site generator (MkDocs, Docusaurus, mdBook)?
- **→ Ask:** Is there documentation beyond the README that needs a home?
  Do they want a docs site?

### 7. Changelog
How are changes communicated to users?
- **CHANGELOG.md** — manually curated or auto-generated.
- **Conventional commits** + tools like `git-cliff`, `release-please`,
  `standard-version` to generate changelogs.
- **GitHub Releases** — release notes per tag.
- **→ Ask:** Do they want a changelog? Manual or automated?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  based on the detected ecosystem and explain why.
- Generate files one at a time as decisions are made.
- README should be useful on day one — don't over-template it.
- Prefer language-standard doc tools over third-party when available.
- Suggest `just docs` recipe if a justfile exists.
"#;

pub(crate) fn guide_docs(repo_root: &Path) -> String {
    let has_readme = repo_root.join("README.md").exists();
    let has_license = repo_root.join("LICENSE").exists() || repo_root.join("LICENSE.md").exists();
    let has_contributing = repo_root.join("CONTRIBUTING.md").exists();
    let has_gitignore = repo_root.join(".gitignore").exists();
    let has_docs_dir = repo_root.join("docs").is_dir();
    let doc_tool = detect_doc_tool(repo_root);

    let mut present = Vec::new();
    let mut missing = Vec::new();
    for (name, exists) in [
        ("README.md", has_readme),
        ("LICENSE", has_license),
        ("CONTRIBUTING.md", has_contributing),
        (".gitignore", has_gitignore),
        ("docs/", has_docs_dir),
    ] {
        if exists {
            present.push(name);
        } else {
            missing.push(name);
        }
    }

    let doc_tool_line = doc_tool.as_deref().unwrap_or("none detected");

    let present = if present.is_empty() {
        "none".to_string()
    } else {
        present.join(", ")
    };
    let missing = if missing.is_empty() {
        "none".to_string()
    } else {
        missing.join(", ")
    };
    DOCS_GUIDE
        .replace("{present}", &present)
        .replace("{missing}", &missing)
        .replace("{doc_tool_line}", doc_tool_line)
}
