//! Topic guides for `wai way <topic>`.

const GH_GUIDE: &str = r#"> *Facilitation guide generated by `wai way gh` — instructs an LLM to lead an interactive discussion with the user.*

# GitHub CLI Integration Guide

**TL;DR**: Walk through 6 topics to set up the GitHub CLI. For each: explain
what it enables, ask if the user wants it, configure it. By the end, the user
will have gh installed, authenticated, and customized for their workflow.
Current state: {current_state}.

You are helping the user set up and configure the GitHub CLI (`gh`) for
this repository. Walk through the topics below **one at a time**.

## Current State

- **gh status**: {current_state}

## Discussion Topics

### 1. Installation & Auth
- **Install**: `brew install gh`, `dnf install gh`, `scoop install gh`,
  or download from https://cli.github.com
- **Auth**: `gh auth login` — choose HTTPS or SSH, browser or token.
- **Multiple accounts**: `gh auth login --hostname` for GitHub Enterprise.
- **→ Ask:** Is gh installed? Do they use github.com or GitHub Enterprise?
  HTTPS or SSH?

### 2. Default Repository Settings
Configure defaults for this repo:
- `gh repo set-default` — set the default remote for `gh` commands.
- **→ Ask:** Is the remote already set up? Do they need to fork a repo
  or work on the origin directly?

### 3. PR Workflow
Do they want to manage pull requests from the CLI?
- `gh pr create` — create PRs from the CLI with title, body, reviewers.
- `gh pr checkout <number>` — check out a PR locally.
- `gh pr merge` — merge with squash, rebase, or merge commit.
- `gh pr view --web` — open PR in browser.
- **→ Ask:** Do they prefer squash, rebase, or merge commits? Default
  reviewers? PR template?

### 4. Issue Management
Do they want to manage issues from the CLI?
- `gh issue create` — create issues from CLI.
- `gh issue list` — list and filter issues.
- `gh issue close` — close from CLI.
- Useful for scripting: `gh issue list --json number,title,labels`
- **→ Ask:** Do they use GitHub Issues? Would CLI issue management help
  their workflow?

### 5. GitHub Actions from CLI
Do they want to interact with CI from the terminal?
- `gh run list` — see recent workflow runs.
- `gh run watch` — live-tail a running workflow.
- `gh run rerun` — retry a failed run.
- `gh workflow run` — trigger a workflow manually.
- **→ Ask:** Do they interact with CI from the terminal? Would watching
  runs or re-triggering failures be useful?

### 6. Extensions & Aliases
- **Aliases**: `gh alias set` — short commands for common operations.
  e.g. `gh alias set prc 'pr create --fill'`
- **Extensions**: community plugins. `gh extension install <repo>`.
  Popular: `gh-dash` (dashboard), `gh-copilot`, `gh-poi` (clean branches).
- **→ Ask:** Any repetitive `gh` commands that could be aliased? Interested
  in any extensions?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  and explain why.
- gh is most valuable when the project already uses GitHub for hosting.
- Suggest aliases for the team's most common operations.
- For AI-assisted workflows, `gh pr create` and `gh run watch` are
  the most impactful commands.
- Don't over-configure — gh works well with minimal setup.
"#;

pub(crate) fn guide_gh() -> String {
    let gh_installed = std::process::Command::new("gh")
        .arg("--version")
        .output()
        .ok()
        .is_some_and(|o| o.status.success());

    let gh_authed = gh_installed
        && std::process::Command::new("gh")
            .args(["auth", "status"])
            .output()
            .ok()
            .is_some_and(|o| o.status.success());

    let current_state = if gh_authed {
        "gh installed and authenticated"
    } else if gh_installed {
        "gh installed but not authenticated"
    } else {
        "gh not installed"
    };
    GH_GUIDE.replace("{current_state}", current_state)
}
