//! Topic guides for `wai way <topic>`.

use std::path::Path;
const HOOKS_GUIDE: &str = r#"> *Facilitation guide generated by `wai way hooks` — instructs an LLM to lead an interactive discussion with the user.*

# Pre-commit Hooks Guide

**TL;DR**: Walk through 8 topics to set up pre-commit quality gates. For each:
explain trade-offs, ask the user's preference, generate config. By the end,
the user will have a working hook configuration with formatting, linting,
and quality checks. Current state: {current_state}.

You are helping the user set up pre-commit quality gates for this repository.
Walk through the topics below **one at a time**, asking the user about their
preferences before generating configuration.

## Current State

- **Hook manager**: {current_state}
- **Ecosystems**: {ecosystem_line}
- **Typos config**: {typos}
- **Vale config**: {vale}

## Discussion Topics

### 1. Hook Manager
Which tool should manage git hooks?
- **prek** — simple TOML config, runs commands directly, no ecosystem lock-in.
  Good for polyglot repos. https://github.com/chshersh/prek
- **lefthook** — YAML config, parallel execution, skip conditions, mature.
  https://github.com/evilmartians/lefthook
- **husky** — JS ecosystem standard, npm-based. Best if repo is Node-only.
- **pre-commit (framework)** — Python-based, huge hook library, language-agnostic.
  Heavier setup but great plugin ecosystem.
- **→ Ask:** Do they have a preference? Any constraints (e.g. can't install Python)?

### 2. Hook Stages
Which git hooks should run checks?
- **pre-commit** — most common, runs before each commit. Fast checks only.
- **pre-push** — runs before push. Good for slower checks (full test suite).
- **commit-msg** — validate commit message format (conventional commits?).
- **→ Ask:** Do they want fast feedback on commit, thorough checks on push, or both?

### 3. Code Formatting
Formatting should be the first check — it's fast and unambiguous.
- Rust: `cargo fmt --check`
- JS/TS: `prettier --check .` or `biome check`
- Python: `ruff format --check` or `black --check`
- Go: `gofmt -l .` or `goimports`
- **→ Ask:** Which formatter do they use? Should the hook auto-fix or just check?

### 4. Linting
Catch bugs and enforce code style beyond formatting.
- Rust: `cargo clippy -- -D warnings`
- JS/TS: `eslint` or `biome lint`
- Python: `ruff check` or `flake8`
- Go: `golangci-lint run`
- **→ Ask:** Which linters? How strict — warnings or errors? Should linting
  block the commit or just warn?

### 5. Spell Checking (typos)
Catch typos in source code, comments, docs, and filenames.
- Tool: `typos` — fast, low false-positive rate, works on any language.
  https://github.com/crate-ci/typos
- Config file: `_typos.toml` (underscore prefix = local overrides)
- **→ Ask:** Do they want spell checking? Any domain words to add to the
  allow list? Should it cover all files or specific extensions?

### 6. Prose Linting (vale)
Enforce writing style in documentation and markdown.
- Tool: `vale` — configurable, supports style guides (Microsoft, Google,
  write-good). https://vale.sh
- **→ Ask:** Do they have a writing style guide? Which file types should
  it cover (*.md, *.txt, *.rst)? How strict — suggestion vs error?

### 7. Other Checks
Depending on the project, consider:
- **Security**: `cargo audit`, `npm audit`, `pip-audit` — check for
  known vulnerabilities in dependencies.
- **Secrets**: `gitleaks` or `detect-secrets` — prevent committing
  API keys, tokens, passwords.
- **File hygiene**: trailing whitespace, EOF newline, large file detection.
- **Commit message**: conventional commits format? (`commitlint`)
- **→ Ask:** Any of these relevant? Which ones matter most?

### 8. Performance
Pre-commit hooks must be fast or developers will skip them.
- Run checks only on staged files when possible (not the whole repo).
- Parallel execution — does the hook manager support it?
- Move slow checks (full test suite, coverage) to pre-push or CI only.
- **→ Ask:** What's an acceptable wait time? (target: under 5-10 seconds
  with warm caches)

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults
  based on the detected ecosystem and explain why.
- Generate config for the chosen hook manager incrementally.
- Suggest the lightest effective checks — don't overload pre-commit.
- If a formatter can auto-fix, suggest running it in fix mode and
  re-staging, rather than just failing.
- Include install instructions (e.g. `prek install`, `lefthook install`).
"#;

fn detect_hook_manager(repo_root: &Path) -> &'static str {
    let prek = repo_root.join("prek.toml").exists();
    let lefthook =
        repo_root.join("lefthook.yml").exists() || repo_root.join("lefthook.yaml").exists();
    let husky = repo_root.join(".husky").is_dir();
    let precommit = repo_root.join(".pre-commit-config.yaml").exists();

    if prek {
        "prek detected (prek.toml)"
    } else if lefthook {
        "lefthook detected (lefthook.yml)"
    } else if husky {
        "husky detected (.husky/)"
    } else if precommit {
        "pre-commit framework detected (.pre-commit-config.yaml)"
    } else {
        "No git hook manager detected"
    }
}

fn detect_lint_config(repo_root: &Path) -> (&'static str, &'static str) {
    let has_typos_config = repo_root.join("typos.toml").exists()
        || repo_root.join("_typos.toml").exists()
        || repo_root.join(".typos.toml").exists();
    let has_vale_config =
        repo_root.join(".vale.ini").exists() || repo_root.join("vale.ini").exists();

    let typos = if has_typos_config {
        "detected"
    } else {
        "not configured"
    };
    let vale = if has_vale_config {
        "detected"
    } else {
        "not configured"
    };
    (typos, vale)
}

fn detect_ecosystem_line(repo_root: &Path) -> String {
    let has_cargo = repo_root.join("Cargo.toml").exists();
    let has_package_json = repo_root.join("package.json").exists();
    let has_go_mod = repo_root.join("go.mod").exists();
    let has_pyproject = repo_root.join("pyproject.toml").exists();

    let mut ecosystems = Vec::new();
    if has_cargo {
        ecosystems.push("Rust");
    }
    if has_package_json {
        ecosystems.push("Node.js");
    }
    if has_go_mod {
        ecosystems.push("Go");
    }
    if has_pyproject {
        ecosystems.push("Python");
    }

    if ecosystems.is_empty() {
        "No recognized language ecosystem detected.".to_string()
    } else {
        ecosystems.join(", ")
    }
}

pub(crate) fn guide_hooks(repo_root: &Path) -> String {
    let current_state = detect_hook_manager(repo_root);
    let (typos, vale) = detect_lint_config(repo_root);
    let ecosystem_line = detect_ecosystem_line(repo_root);
    HOOKS_GUIDE
        .replace("{current_state}", current_state)
        .replace("{ecosystem_line}", &ecosystem_line)
        .replace("{typos}", typos)
        .replace("{vale}", vale)
}
