//! Topic guides for `wai way <topic>`.

use std::path::Path;
const ISSUES_GUIDE: &str = r#"> *Facilitation guide generated by `wai way issues` — instructs an LLM to lead an interactive discussion with the user.*

# Issue Tracking Guide

**TL;DR**: Walk through 6 topics to set up issue tracking. For each: explain
trade-offs, ask the user's preference, recommend a setup. By the end, the user
will have a tracking tool chosen and configured with structure, labels, and workflow.
Current state: {current_state}.

You are helping the user set up issue tracking for this repository.
Walk through the topics below **one at a time**, asking about their
team size, workflow, and preferences before recommending a setup.

## Current State

- **Tracking**: {current_state}

## Discussion Topics

### 1. Tracking Tool
Where should issues live?
- **GitHub Issues** — built into GitHub, free, good for open source.
  Labels, milestones, projects. Limited dependency tracking.
- **Linear** — fast, opinionated, great for small teams. Cycles,
  projects, triage workflows. Not free.
- **Jira** — enterprise standard, powerful but complex. Custom workflows,
  deep integrations. Can be overkill for small projects.
- **beads** — local-first, lives in the repo (.beads/). Good for
  solo/AI-assisted work. Dependencies, priorities, no external service.
- **Plain markdown** — `TODO.md` or `docs/tasks.md`. Simple but
  no status tracking or assignment.
- **→ Ask:** Is this solo work, a small team, or a large org? Do they need
  external visibility (stakeholders, open source community)?

### 2. Issue Structure
What goes in an issue?
- **Title** — clear, actionable (verb + noun: "Add caching to API")
- **Description** — why this needs doing, acceptance criteria, context
- **Type** — bug, feature, task, chore, spike/research
- **Priority** — how urgent? (P0-P4, or high/medium/low)
- **Size/effort** — t-shirt sizes, story points, or skip it?
- **→ Ask:** How detailed should issues be? Do they want templates?

### 3. Labels & Categories
How to organize issues beyond type and priority.
- **Area labels**: `frontend`, `backend`, `infra`, `docs`
- **Status labels**: `needs-triage`, `ready`, `blocked`, `wontfix`
- **Effort labels**: `good-first-issue`, `quick-win`, `epic`
- **→ Ask:** What categories make sense for this project? Keep it minimal —
  too many labels means none get used.

### 4. Workflow & States
How does an issue move from creation to completion?
- Basic: `open` → `in_progress` → `closed`
- Kanban: `backlog` → `ready` → `in_progress` → `review` → `done`
- **→ Ask:** How many states do they need? Who moves issues between states?
  Should there be a triage step?

### 5. Dependencies & Blocking
Do issues depend on each other?
- Some tools support explicit dependency links (beads, Linear, Jira).
- GitHub Issues: use "blocked by #123" in description (manual).
- **→ Ask:** Do they need dependency tracking? Or is it simple enough
  that ordering the backlog suffices?

### 6. Templates & Automation
- **Issue templates**: pre-filled forms for bug reports, feature requests.
  (GitHub supports `.github/ISSUE_TEMPLATE/`)
- **Auto-labeling**: label PRs/issues based on file paths changed.
- **Stale bot**: auto-close old issues after inactivity.
- **→ Ask:** Do they want issue templates? Any automation?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults:
  solo/AI → beads, small team → Linear or GitHub Issues, open source →
  GitHub Issues, enterprise → Jira.
- Match tool complexity to team size.
- Start with minimal labels — add more only when you feel the pain.
- Write issues for your future self — include enough context to
  pick them up cold.
- If using beads, remind them to `bd dolt push` to sync.
"#;

pub(crate) fn guide_issues(repo_root: &Path) -> String {
    let has_beads = repo_root.join(".beads").is_dir();
    let has_github = repo_root.join(".github").is_dir();

    let current_state = if has_beads {
        "beads detected (.beads/) — local-first issue tracking"
    } else if has_github {
        "GitHub repository detected — GitHub Issues available"
    } else {
        "No issue tracking detected"
    };
    ISSUES_GUIDE.replace("{current_state}", current_state)
}
