//! Topic guides for `wai way <topic>`.

use std::path::Path;
const SPECS_GUIDE: &str = r#"> *Facilitation guide generated by `wai way specs` — instructs an LLM to lead an interactive discussion with the user.*

# Change Proposals & Specs Guide

**TL;DR**: Walk through 6 topics to set up a design decision tracking system.
For each: explain trade-offs, ask the user's preference, set up the structure.
By the end, the user will have a proposal format, review process, and lifecycle
configured. Current state: {current_state}.

You are helping the user set up a system for managing design decisions and
change proposals. Walk through the topics below **one at a time**, asking
about their team's decision-making process.

## Current State

- **Proposal system**: {current_state}

## Discussion Topics

### 1. Why Track Decisions
If the user isn't sure they need this, discuss why before choosing a tool:
- **Architecture Drift** — without records, the codebase drifts from
  its intended design. New contributors reinvent or contradict past decisions.
- **Onboarding** — new team members can read *why* things are the way
  they are, not just *what* the code does.
- **Review** — proposals create a review checkpoint before big changes.
- **→ Ask:** What's driving this? Past mistakes, growing team, compliance,
  or just good hygiene?

### 2. Proposal Format
Which format fits their workflow?
- **ADRs (Architecture Decision Records)** — lightweight markdown files.
  Status, Context, Decision, Consequences. One file per decision.
  Standard: https://adr.github.io
- **RFCs** — more structured proposals with problem statement, alternatives
  considered, detailed design. Good for larger teams.
- **openspec** — specification-driven proposals with capabilities, changes,
  tasks, and strict validation. Good for AI-assisted development where
  specs guide implementation. https://github.com/Fission-AI/OpenSpec
- **→ Ask:** How formal do they need? ADRs for lightweight, RFCs for mid-weight,
  openspec for spec-driven development.

### 3. When to Write a Proposal
Not every change needs a proposal. Define the threshold:
- **Always**: breaking changes, new capabilities, architecture shifts,
  security changes, major dependency additions.
- **Never**: bug fixes, small features, refactors within existing patterns.
- **Gray area**: performance work, large migrations, workflow changes.
- **→ Ask:** What kinds of changes should require a proposal? Who decides
  when one is needed?

### 4. Review Process
How are proposals reviewed and approved?
- **PR-based** — proposal is a PR, reviewed like code. Merged = approved.
- **Meeting-based** — discuss in a design review meeting. Document outcome.
- **Lazy consensus** — post it, wait N days, ship if no objections.
- **Owner approval** — designated area owners approve proposals.
- **→ Ask:** How does the team make decisions today? What level of formality?

### 5. Lifecycle & Archival
What happens after a proposal is implemented?
- **Status field**: proposed → approved → implemented → archived/superseded.
- Keep completed proposals as historical record.
- When a decision is reversed, write a new proposal that supersedes
  the old one (don't edit history).
- **→ Ask:** Do they want lifecycle tracking? Should old proposals be
  archived or kept in the main directory?

### 6. Integration with Code
How do proposals connect to implementation?
- Reference proposal ID in commit messages and PRs.
- Link tasks/issues to proposals (e.g. beads issues referencing
  openspec changes).
- Some teams add a "Decision" comment in code pointing to the ADR.
- **→ Ask:** How tightly should proposals link to code? Should there be
  task tracking integration?

## Guidelines

- If the user says they already have something or want to skip a topic, move on.
- If the user is unsure or says "just pick for me", suggest sensible defaults:
  ADRs for most teams, openspec for spec-driven AI development.
- Number proposals sequentially for easy reference.
- Store proposals in the repo (not a wiki) so they're versioned
  alongside the code they describe.
- The first proposal should document the decision to use proposals.
"#;

pub(crate) fn guide_specs(repo_root: &Path) -> String {
    let has_openspec = repo_root.join("openspec").is_dir();
    let has_docs_decisions =
        repo_root.join("docs/decisions").is_dir() || repo_root.join("docs/adr").is_dir();
    let has_rfcs = repo_root.join("rfcs").is_dir() || repo_root.join("docs/rfcs").is_dir();

    let current_state = if has_openspec {
        "openspec detected (openspec/)"
    } else if has_rfcs {
        "RFCs directory detected"
    } else if has_docs_decisions {
        "ADR directory detected"
    } else {
        "No change proposal system detected"
    };
    SPECS_GUIDE.replace("{current_state}", current_state)
}
